cp-ksql-server/include/etc/confluent/docker/log4j.properties.template
Same change made in ksql: https://github.com/confluentinc/ksql/pull/4302
=> perf: Avoids logging INFO for rest-util requests, since it hurts pull query performance

cp-ksql-cli/Dockerfile.deb9, cp-ksql-cli/Dockerfile.ubi8, cp-ksql-server/Dockerfile.deb9, cp-ksql-server/Dockerfile.ubi8
^ for consistency with the community ksqlDB images (https://github.com/confluentinc/ksql/pull/4729).
Slack conversation: https://confluent.slack.com/archives/C8486MR1C/p1584107074300800?thread_ts=1584048653.296300&cid=C8486MR1C
Note that this change is targeted at master and not 5.5, so the change will only be available starting in 6.0 (or whatever the next release after 5.5 is).
=> Minor: add confluent-hub to ksqldb server and cli images

cp-ksqldb-server/include/etc/confluent/docker/configure, cp-ksqldb-server/include/etc/confluent/docker/launch, cp-ksqldb-server/include/etc/confluent/docker/run
`export KSQL_LOG4J_OPTS="-Dlog4j.configuration=file:/etc/${COMPONENT}/log4j.properties"` is being called in `/etc/confluent/docker/configure` but it's being executed in a subshell of the run script, so it's not present when actually starting up the server in `/etc/confluent/docker/launch`
Moved setting the environment variable to the launch script
Verified this works with the clickstreams demo (embedded connect logs show up in docker-compose logs). Removed these two environment variables from the docker-compose and it still showed.
```
KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql-server/log4j.properties"
KSQL_LOG4J_ROOT_LOGLEVEL: INFO
```
Used this image: confluent-docker.jfrog.io/confluentinc/cp-ksqldb-server:steven-ksqldb-server-log4j-fix …
=> properly set KSQL_LOG4J_OPTS for launching server

cp-ksql-cli/include/etc/confluent/docker/configure, cp-ksql-server/include/etc/confluent/docker/run
We don't want to print the environment variables in the logs during startup because they contain sensitive data.
=> ST-3599: Remove show_env function because it exposes secrets

cp-ksqldb-cli/Dockerfile.deb9, cp-ksqldb-cli/Dockerfile.ubi8, cp-ksqldb-server/Dockerfile.deb9, cp-ksqldb-server/Dockerfile.ubi8
- Product decision to no longer bundle confluent-hub in images
- The way it was written meant that version X of ksql images would always include version X-1 of confluent hub
Context: https://confluent.slack.com/archives/C8486MR1C/p1594756787467400
=> SEC-1034: remove hub-client from ksql images

cp-ksqldb-cli/Dockerfile.ubi8, cp-ksqldb-server/Dockerfile.ubi8
This reverts commit 783ac1b8c0cc0b69b83215dcc9fe4e3239adeb41.
A more thorugh workaround or decision needs to be made.
In the meantime, reverting the commit so that other internal
demo related activites can continue as usual.
=> [KSQL-5184] Revert "SEC-1034: remove hub-client from ksql images (#52)"

Jenkinsfile, cp-ksqldb-cli/Dockerfile.ubi8, cp-ksqldb-server/Dockerfile.ubi8, cp-ksqldb-server/pom.xml
One approach to fixing a couple of issues with ksqlDB images in 6.0 . 
Known issues:
- We need the 6.0 version of the confluent hub client as the previous version has a CVE (the image currently pulls only publicly available images)
- Permissions / File locations for using the confluent hub client for connect need to be modified to work with UBI8
- Currently connecting to MDS for ksqlDB via https is broken in docker due to kafka-clients-CCS and kafka-clients-CE ending up in the same directory (and it looks like CCS gets picked up via classpath)
See: https://confluentinc.atlassian.net/browse/KSQL-5246 and https://confluentinc.atlassian.net/browse/ST-4097
This approach:
- installs both confluent-security and confluent-hub from rpm packaging
- creates required directories and sets permissions …
=> Install security plugins and hub client from packages

Jenkinsfile, cp-ksqldb-cli/Dockerfile.ubi8, cp-ksqldb-cli/pom.xml, cp-ksqldb-examples/Dockerfile.ubi8, cp-ksqldb-examples/pom.xml, cp-ksqldb-server/Dockerfile.ubi8, cp-ksqldb-server/pom.xml, pom.xml
Setting the jenkins config to use nano versioning. Removed all of the snapshot versions and replaced with nano versions. Updated all of the dependency versions.
I had to adjust the docker image files as well because the wild card that is used to copy the ksql artifacts to the image did not work for the nano versioned artifacts.
These changes will be merged during phase two of the nano versioning roll out.
=> ST-3461: Nano versioning

cp-ksqldb-server/test/fixtures/basic-cluster.yml
- SR now requires KAFKASTORE_BOOTSTRAP_SERVERS to boot
The 7.0.x and master jobs are failing:
```
==================================== ERRORS ====================================
15:47:04  ______________ ERROR at setup of KsqlServerTest.test_server_start ______________
15:47:04  [gw0] linux -- Python 3.6.12 /var/tmp/confluent/bin/python
15:47:04  
15:47:04  cls = <class 'test_ksql_server.KsqlServerTest'>
15:47:04  
15:47:04      @classmethod
15:47:04      def setup_class(cls):
15:47:04          cls.cluster = utils.TestCluster(
15:47:04              "ksql-server-test", FIXTURES_DIR, "basic-cluster.yml")
15:47:04          cls.cluster.start()
15:47:04          try:
15:47:04              start = time.time()
15:47:04              while time.time() - start < 30:
15:47:04  >               if …
```
=> build: SR requires KAFKASTORE_BOOTSTRAP_SERVERS settings

cp-ksqldb-server/Dockerfile.ubi8
Some image scanning tools that check for vulnerabilities and OCI image best
practices expect to find a `description` label on images that is _not_ inherited
from base images. The proposed change addresses this requirement.
=> Add description label to ksqlDB server Dockerfile

cp-ksql-cli/Dockerfile.ubi8, cp-ksql-server/Dockerfile.ubi8
The changes is for making images openshift compliant. In line with similar merges to kafka-images (https://github.com/confluentinc/kafka-images/pull/139)
Updates the rebase branch
=> Fix directory permission

cp-ksqldb-server/include/etc/confluent/docker/log4j.properties.template
Testing done:
`log4j.template`:
```
{% set kr_props = env_to_props('LOG4J_', '') -%}
{% for name, value in kr_props.items() -%}
{{name}}={{value}}
{% endfor -%}
```
Console:
```
% export LOG4J_LOG4J_FOO_BAR='baz'
% python3.9 -i confluent/docker_utils/dub.py
>>> fill_and_write_template('/Users/almog.gavra/dev/confluent/confluent-docker-utils/log4j.template', '/Users/almog.gavra/dev/confluent/confluent-docker-utils/log4j.properties')
True
% cat log4j.properties
log4j.foo.bar=baz
```
=> feat: allow users to set custom log4j configs

pom.xml
netty versions are up-managed in ksql-parent maven project, from the common maven project. However, the ksql-images-parent project does not get the overrides, because it does not derive from ksql-parent but from common-docker.
Without larger structural changes, we need to up-manage the versions in this maven project as well.
=> chore: manage netty versions

Jenkinsfile
It's nice to have build failure alerts for master to go to #ksqldb-quality-oncall, but for old branches we should send the alerts to #ksqldb-warn in order to avoid spamming #ksqldb-quality-oncall. This used to be the case previously, which is why 7.0.x and earlier are already sending alerts to #ksqldb-warn. When new branches are cut, they need to be updated.
=> Update slack channel to ksqldb-warn

pom.xml
This PR upgrades netty to 4.1.00.Final and netty-tcnative-version to 2.0.61.Final to address https://nvd.nist.gov/vuln/detail/CVE-2023-44487.
4.1.100.Final address the vulnerability according to https://netty.io/news/2023/10/10/4-1-100-Final.html.
also: https://github.com/confluentinc/ksql/pull/10080
=> chore: Upgrade netty to 4.1.100.Final for CVE-2023-44487

pom.xml
Backport of #105 for CP releases for CVE-2023-44487
=> chore: Upgrade netty to 4.1.100.Final to address CVE-2023-44487

cp-ksqldb-cli/Dockerfile.ubi8, cp-ksqldb-examples/Dockerfile.ubi8, cp-ksqldb-server/Dockerfile.ubi8
As part of [FedRAMP M3](https://confluentinc.atlassian.net/browse/FEDRAMP-216) Container Hardening Requirements mentioned in this [doc](https://confluentinc.atlassian.net/wiki/spaces/~578374643/pages/3126199411/FedRAMP+Container+Hardening+Requirements), using [ADD](https://confluentinc.atlassian.net/wiki/spaces/~578374643/pages/3126199411/FedRAMP+Container+Hardening+Requirements#Ensure-that-COPY-is-used-instead-of-ADD-in-Dockerfiles-(Manual)) command is restricted in Dockerfiles.
This PR replaces ADD with COPY in docker files.
https://confluentinc.atlassian.net/browse/KSQL-11502
=> chore: replace ADD with COPY in docker files

cp-ksqldb-examples/pom.xml, pom.xml
I could not test this change. The idea is to disable writing testMetadata to avoid the Jenkins job failing.
=> fix: attempt to disable writing test metadata

pom.xml
- Previous [version change](https://github.com/confluentinc/ksql-images/commit/ef47898f59b9c60f1f7b6f1c85449bbc69608a63) of cause [build failure](https://jenkins.confluent.io/job/confluentinc/job/ksql-images/job/7.5.x/259/) 
- This PR reverts the version change to unblock the build
=> [hotfix] revert the version change to unblock the build failure

pom.xml
- The build of 7.3.x is failed due to the [version change of org.apache.commons](https://github.com/confluentinc/ksql-images/commit/b55fc7554cc6ecaf44b8a109babfb05ff71b8ebe).
- This PR reverts the version change to fix the failure.
=> [hotfix] Revert the version change to fix the build failure of 7.3.x

service.yml
`push_latest: true` is needed to fix the below error as per this documentation: https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3211693075/Jenkins+-+Semaphore+self+migration+guide#How-do-I-migrate-dockerfile%3F
```
>       raise cls(e, response=response, explanation=explanation)08:27
E       docker.errors.NotFound: 404 Client Error: Not Found ("manifest for 519856050701.dkr.ecr.us-west-2.amazonaws.com/docker/prod/confluentinc/cp-ksqldb-server:dev-6.2.x-95e22bb6-ubi8.amd64 not found: manifest unknown: Requested image not found")08:27
/var/tmp/confluent/lib/python3.7/site-packages/docker/errors.py:31: NotFound
```
After this PR is merged, cc-service-bot will need to be run in this repo and the resulting Semaphore config changes will need to be backported to the version branches
=> Add Push Latest to service.yml

cp-ksqldb-server/requirements.txt
Update confluent-docker-utils as python version was bumped up to 3.12
Python version was bumped up from 3.7 because the semaphore job could not download the deps.
=> MINOR: Update confluent-docker-utils as python version was bumped up to 3.12

.semaphore/cp_dockerfile_build.yml, .semaphore/semaphore.yml, cp-ksqldb-server/requirements.txt, service.yml
This PR pins the python version to 3.8 which is compatible with the pip version >= 10 and confluent-docker-utils v30
=> KSQL-12385 | Fix the python version to 3.8 which is compatible with confluent-docker-utils v30

pom.xml
Fix CVE for netty-common and bump it to version 4.1.115.
=> KSQL-12807 | Fix CVE for netty-common and bump it to version 4.1.115.

.semaphore/cp_dockerfile_build.yml
We have made the build environment for nightly and RC pipelines similar in #180. This change caused failures in last stage (deploy maven) which was fixed in #192 . Now since the maven configs point to codeartifact, the failures occurred as it is trying to fetch jars from codeartifact which is conflicting with the jars built in previous stages.
This PR fixes build [failures](https://semaphore.ci.confluent.io/jobs/558f8e67-c325-41fb-b346-abad94d7e664) on 7.1.x docker images by clearing the maven cache
The failures occurred due to `Artifact io.confluent:common-docker:pom:7.1.16-0 is present in the local repository, but cached from a remote repository ID that is unavailable in current build context`
=> Clear maven cache

pom.xml
Pin the netty version to be in line with ksql repo 7.1.x branch.
=> KSQL-13089 | Pin the netty version to be in line with ksql repo 7.1.x branch.

cp-ksqldb-server/test/fixtures/basic-cluster.yml, cp-ksqldb-server/test/test_ksql_server.py
Fix the kafka-ready command and mention the cluster id for the KRaft cluster.
=> KSQL-13103 | Fix the kafka-ready command and mention the cluster id for the KRaft cluster.

cp-ksqldb-examples/Dockerfile.ubi8, cp-ksqldb-server/Dockerfile.ubi8
Remove unwanted jars from cp-ksqldb-server docker image
This PR removes the `confluent-security` dependencies for schema registry, connect and kafka-rest and keeps only the one for ksql.
=> KSQL-12617 | Remove unwanted jars from cp-ksqldb-server docker image

cp-ksqldb-server/test/fixtures/basic-cluster.yml
As part of CP 8.0, cp-enterprise-kafka image is getting deprecated in favour of cp-server
=> using cp-server image for running ksql docker tests

cp-ksqldb-cli/include/etc/confluent/docker/log4j2.yaml.template
Fix log folder name for cli image. log4j yaml expects dynamic properties to set explicitly
=> [KSQL-13251] |  Fix log folder name for cli

cp-ksqldb-server/include/etc/confluent/docker/connect.properties.template, cp-ksqldb-server/include/etc/confluent/docker/ksqldb-server.properties.template
envToProps now takes additional arguments to skip properties that have been already defined
This PR fixes the call to envToProps with the correct number of properties
=> update template with latest envToProps

cp-ksqldb-server/Dockerfile.ubi9
This PR fixes the empty values set for some of the labels. 
In Dockerfile, ARGS defined in any of the previous stages is not available in the stage that is being built. Due to this, some labels were not getting set correctly. 
Once this PR is merged, this change will also be cherry-picked to 8.0.0 versioned release branch.
=> CPBR-2644: fixing labels for refreshed cp-ksqldb-server image

cp-ksqldb-server/Dockerfile.ubi9
(cherry picked from commit 8edc1dea31b499603e6c66b57210b7f87eabfb99)
cherry picked changes from PR merged in 8.0.x branch - https://github.com/confluentinc/ksql-images/pull/232
=> CPBR-2644: fixing labels for refreshed ksql images (#232)

service.yml
packages apart from cp-ksqldb-server are failing to deploy/publish due to missing codeartifacts package path. This PR addresses this
=> Update code artifact package paths for versions below 8.1.x

.semaphore/cp_dockerfile_build.yml, service.yml
This pull request makes a minor update to the Maven build phase in the service.yml configuration, changing it to only run the package phase instead of both package and integration-test.
Reason to skip:
Given that these sanity tests don't add much value as the docker images are tested in CFK tests anyways, we can follow other components and remove these tests.
Another reason to skip: https://confluentinc.atlassian.net/browse/CPBR-2658
=> Inc 5549 8 0 x
