cp-ksqldb-cli/pom.xml
cp-ksqldb-server/pom.xml

Add ksqldb-tools to pom files

---

pom.xml

We need to pint merge to master.

Override commons-compress and commons-codec

---

cp-ksqldb-cli/pom.xml

Fix dependabot alerts: https://github.com/confluentinc/ksql-images/security/dependabot/cp-ksqldb-cli/pom.xml/junit:junit/open

Upgrade Junit to 4.13.1

---

cp-ksql-cli/pom.xml
cp-ksql-examples/pom.xml
cp-ksql-server/pom.xml

Bump Jakarta to 4.0.0 due to CVE-2021-28170

fix CVE-2021-28170

---

.github/CODEOWNERS

https://confluentinc.atlassian.net/browse/KSE-750

chore: add CODEOWNERS file (MINOR)

---

pom.xml

Required for https://github.com/confluentinc/ksql/pull/9764
cc: @lucasbru

[KSE-1612] Upgrade netty to 4.1.86

---

pom.xml

[KSE-1830] | Vedarth Sharma | Fix CVE

---

service.yml

Add sign images true to semaphore

[KSE-1792] | Vedarth Sharma | Add sign_images

---

service.yml

Add task config as mentioned in https://confluentinc.atlassian.net/wiki/spaces/TOOLS/pages/3211693075/Jenkins+-+Semaphore+self+migration+guide#How-do-I-migrate-dockerfile%3F

[KSE-1792] | Vedarth Sharma | Add task config

---

pom.xml

update commons compress to use version in sync with other branches.

update commons, use correct version

---

service.yml

To fix the CodeArtifact access issue

MINOR: Add ref to the CodeArtifact path in service.yml

---

.gitignore
.semaphore/cp_dockerfile_build.yml
.semaphore/semaphore.yml
service.yml

KSQL-12385 | Bump up python version to 3.9

---

service.yml

Add all the modules that are build and artifacts pushed to maven in the access list.

KSQL-12447 | Fix the path for CodeArtifact access.

---

pom.xml

Update netty version from 4.1.112.Final to 4.1.113.Final.

Update netty version from 4.1.112.Final to 4.1.113.Final.

---

pom.xml

Update netty version from 4.1.112.Final to 4.1.113.Final in 7.0.x

Update netty version from 4.1.112.Final to 4.1.113.Final in 7.0_x

---

.semaphore/cp_dockerfile_build.yml

- added separate steps for setting maven configs 
- tested at https://semaphore.ci.confluent.io/workflows/f7a2af39-dbe8-48e8-b871-d2cf0eebdd02?pipeline_id=68e864e7-d26a-4794-b958-7fc9ce6d66b2

fix minor issues with yaml

---

cp-ksqldb-cli/Dockerfile.ubi8
cp-ksqldb-cli/pom.xml
cp-ksqldb-examples/Dockerfile.ubi8
cp-ksqldb-examples/README.md
cp-ksqldb-examples/pom.xml
cp-ksqldb-server/Dockerfile.ubi8
cp-ksqldb-server/include/etc/confluent/docker/configure
cp-ksqldb-server/pom.xml

feat: dockerfile build using ksqldb rpm

---

.semaphore/cp_dockerfile_build.yml

reset maven configs to semaphore's default config during maven deploy stage during cp docker builds

reset maven configs during maven deploy

---

cp-ksqldb-cli/Dockerfile.ubi8
cp-ksqldb-cli/pom.xml
cp-ksqldb-examples/Dockerfile.ubi8
cp-ksqldb-examples/README.md
cp-ksqldb-examples/pom.xml
cp-ksqldb-server/Dockerfile.ubi8
cp-ksqldb-server/include/etc/confluent/docker/configure
cp-ksqldb-server/pom.xml

KSQL-12655
https://github.com/confluentinc/ksql-images/pull/186
_Note: It is failing due to unavailability of common-docker-8.0 and confluent-security-8.0_

feat: dockerfile build using rpm

---

.semaphore/cp_dockerfile_build.yml

changes done in previous PRs for using similar maven configs for nightly and rc pipelines
contains changes from #180 #192 #193

make nightly pipeline same as RC

---

pom.xml

Cherry-pick commits from 7.1.x to 7.1.16

Cherry-pick commits from 7.1.x to 7.1.16

---

cp-ksqldb-server/test/fixtures/basic-cluster.yml
cp-ksqldb-server/test/test_ksql_server.py

Deprecate zookeeper from the test setup.

KSQL-13103 | Deprecate zookeeper from the test setup.

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/semaphore.yml
service.yml

- applied service bot template changes https://github.com/confluentinc/cc-service-bot/pull/1477 to update docker build and docker promote workflows
- added SKIP_COMMUNITY flag/ task param

CPBR-2445 applying service bot changes to 7.1.x branch

---

cp-ksqldb-server/requirements.txt

(cherry picked from commit 3b7551266a5128877d13ac4b823b9758e43f9748)

[KSQL-13417] | Upgrade docker utils to 77 (#240)

---

.semaphore/semaphore.yml

(cherry picked from commit b513c0099edd3f4d6808b88d034bf8533ff13e29)

[KSQL-13417] | Remove integration test (#241)
